### ISSUE TITLE
Setup proper code coverage with source maps 

### ISSUE THREAD

**Issue by igor-ka** [rangle/angular-redux-starter#2]
In es6 world the setup for unit test coverage is achieved by a combination of source maps, karma-coverage as well as istanbul-instrumenter.

This does not seem to work when typescript loader in used in conjunction with webpack.

**Comment by SethDavenport** [comment]
I'm tracking all starter issues in the merged ZenHub board.  Issues are labelled according to the starters they affect.

https://github.com/rangle/react-redux-starter#boards?repos=45710306,46129075,49850682,48808013,49800398

**Comment by SethDavenport** [comment]
Therefore, I'm marking this as a duplicate of https://github.com/rangle/angular2-redux-starter/issues/2.
