### ISSUE TITLE
Fix sourcemaps when generating CSS into a standalone bundle

### ISSUE THREAD

**Issue by igor-ka** [rangle/angular-redux-starter#3]
It is possible to generate css into a stand-alone bundle, and might be preferable in some situation. The steps required to generate a stand-alone css bundle can be found [here](https://github.com/rangle/ng-typescript-webpack-starter.git).

When I tried this, the bundling worked but the source-maps became broken. I could get it to work for either .ts files or .css files, but not both, by playing with css loaders source maps parameter and devtools: source-map option of the webpack config.

**Comment by igor-ka** [comment]
@kosz @neilff @SethDavenport @e-schultz 

There is an issue open for this already on ExtractTextPlugin end, webpack/extract-text-webpack-plugin/issues/119

**Comment by SethDavenport** [comment]
Moved to master issues repo: https://github.com/rangle/rangle-starter/issues/14
